if(NOT DEFINED PUBLIC_INCLUDE_DIR)
    message(FATAL_ERROR "PUBLIC_INCLUDE_DIR is required")
endif()

if(NOT EXISTS "${PUBLIC_INCLUDE_DIR}/HaruFrame")
    message(FATAL_ERROR "HaruFrame public entry header is required")
endif()

file(READ "${PUBLIC_INCLUDE_DIR}/HaruFrame" haru_frame_header)
if(NOT haru_frame_header MATCHES "HARU_FRAME_PUBLIC_INCLUDE")
    message(FATAL_ERROR "HaruFrame must define the public include gate")
endif()

file(GLOB public_headers "${PUBLIC_INCLUDE_DIR}/Haru*")
foreach(public_header IN LISTS public_headers)
    get_filename_component(public_header_name "${public_header}" NAME)
    if(public_header_name STREQUAL "HaruFrame")
        continue()
    endif()

    file(READ "${public_header}" public_header_content)
    if(NOT public_header_content MATCHES "#error")
        message(FATAL_ERROR "${public_header_name} must reject direct inclusion")
    endif()
    if(NOT public_header_content MATCHES "HARU_FRAME_PUBLIC_INCLUDE")
        message(FATAL_ERROR "${public_header_name} must require <HaruFrame>")
    endif()
endforeach()
