set(required_binaries
    CORE_BINARY
    UI_BINARY
    PLATFORM_BINARY
    RESOURCES_BINARY
    LOCALIZATION_BINARY
)

foreach(binary_var IN LISTS required_binaries)
    if(NOT DEFINED ${binary_var})
        message(FATAL_ERROR "${binary_var} is required")
    endif()
    if(NOT EXISTS "${${binary_var}}")
        message(FATAL_ERROR "Engine binary does not exist: ${${binary_var}}")
    endif()
endforeach()

get_filename_component(core_binary_name "${CORE_BINARY}" NAME)
get_filename_component(ui_binary_name "${UI_BINARY}" NAME)
get_filename_component(platform_binary_name "${PLATFORM_BINARY}" NAME)
get_filename_component(resources_binary_name "${RESOURCES_BINARY}" NAME)
get_filename_component(localization_binary_name "${LOCALIZATION_BINARY}" NAME)

if(CMAKE_HOST_WIN32)
    if(NOT core_binary_name STREQUAL "HarufushiEngine.dll")
        message(FATAL_ERROR "Core engine DLL must be HarufushiEngine.dll, got ${core_binary_name}")
    endif()
    if(NOT ui_binary_name STREQUAL "HarufushiEngine.UI.dll")
        message(FATAL_ERROR "UI engine DLL must be HarufushiEngine.UI.dll, got ${ui_binary_name}")
    endif()
    if(NOT platform_binary_name STREQUAL "HarufushiEngine.Platform.dll")
        message(FATAL_ERROR "Platform engine DLL must be HarufushiEngine.Platform.dll, got ${platform_binary_name}")
    endif()
    if(NOT resources_binary_name STREQUAL "HarufushiEngine.Resources.dll")
        message(FATAL_ERROR "Resources engine DLL must be HarufushiEngine.Resources.dll, got ${resources_binary_name}")
    endif()
    if(NOT localization_binary_name STREQUAL "HarufushiEngine.Localization.dll")
        message(FATAL_ERROR "Localization engine DLL must be HarufushiEngine.Localization.dll, got ${localization_binary_name}")
    endif()
else()
    if(NOT core_binary_name MATCHES "^libHarufushiEngine\\.(so|dylib)$")
        message(FATAL_ERROR "Core engine shared library has unexpected name: ${core_binary_name}")
    endif()
    if(NOT ui_binary_name MATCHES "^libHarufushiEngine\\.UI\\.(so|dylib)$")
        message(FATAL_ERROR "UI engine shared library has unexpected name: ${ui_binary_name}")
    endif()
    if(NOT platform_binary_name MATCHES "^libHarufushiEngine\\.Platform\\.(so|dylib)$")
        message(FATAL_ERROR "Platform engine shared library has unexpected name: ${platform_binary_name}")
    endif()
    if(NOT resources_binary_name MATCHES "^libHarufushiEngine\\.Resources\\.(so|dylib)$")
        message(FATAL_ERROR "Resources engine shared library has unexpected name: ${resources_binary_name}")
    endif()
    if(NOT localization_binary_name MATCHES "^libHarufushiEngine\\.Localization\\.(so|dylib)$")
        message(FATAL_ERROR "Localization engine shared library has unexpected name: ${localization_binary_name}")
    endif()
endif()
