if(NOT DEFINED PUBLIC_INCLUDE_DIR)
    message(FATAL_ERROR "PUBLIC_INCLUDE_DIR is required")
endif()

if(NOT EXISTS "${PUBLIC_INCLUDE_DIR}/HaruFrame")
    message(FATAL_ERROR "HaruFrame public entry header is required")
endif()

file(GLOB public_headers "${PUBLIC_INCLUDE_DIR}/Haru*")
foreach(public_header IN LISTS public_headers)
    get_filename_component(public_header_name "${public_header}" NAME)
    file(READ "${public_header}" public_header_content)
    if(public_header_content MATCHES "Include <HaruFrame>")
        message(FATAL_ERROR "${public_header_name} must support direct public inclusion")
    endif()
endforeach()
